name: Update Image FPM
on:
  schedule:
    - cron: "0 1 * * 1" # Every Monday at 1:00 AM
  workflow_dispatch:
# env:
#   IMAGE_NAME: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}"
permissions:
  contents: read
  packages: write
jobs:
  build_image:
    strategy:
      matrix:
        os: [ubuntu-24.04]
        version: ['8.2-fpm', 'latest']
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set lowercase IMAGE_NAME
        run: echo "IMAGE_NAME=$(echo ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
      - name: Define dockerfile
        run: echo "DOCKERFILE=Dockerfile.${{ matrix.version }}" >> $GITHUB_ENV
      - if: matrix.version == 'latest'
        run: echo "DOCKERFILE=Dockerfile" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: "./${{ env.DOCKERFILE }}"
          tags: "${{ env.IMAGE_NAME }}:${{ matrix.version }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max